### ISSUE TITLE
Missing hid_$(OS).c files

### ISSUE THREAD

**Issue by codygon** [jhdewitt/sltk#1]
Attempting to make on Linux, having set OS= LINUX, results in:

make: *** No rule to make target 'hid_LINUX.c', needed by 'hid.o'.  Stop.

I don't believe this file, or hid.h is provided by the listed prerequisites or system.

**Comment by jhdewitt** [comment]
Hello,

These files are from PJRC teensy USBHID library: https://www.pjrc.com/teensy/rawhid.html

Will update repo with these files and docs.

**Comment by jhdewitt** [comment]
If the addition of hid_* files don't allow compilation on your Linux, please share any other errors. Closing for now. Thanks for the report.
