### ISSUE TITLE
slcapture.py from terminal

### ISSUE THREAD

**Issue by prahjister** [jhdewitt/sltk#6]
When i run from a terminal I get 

prahjister@amlogic:~/sltk-master$ python slcapture.py
Traceback (most recent call last):
  File "slcapture.py", line 16, in <module>
    from OSC import OSCServer, OSCClient, OSCMessage, OSCStreamingClient
ImportError: No module named OSC

**Comment by jhdewitt** [comment]
Got so focused on C++ dependencies, python deps totally slipped my mind.

`slcapture.py` has two only external dependencies: opencv (you have, i think) and pyOSC https://github.com/ptone/pyosc

I have updated the Compilation Guide with details on how to install pyOSC https://github.com/jhdewitt/sltk/wiki/Compilation-Guide


>Next up, python dependency for `slcapture.py`:

10. `git clone https://github.com/ptone/pyosc`

11. `cd pyosc`

11. `sudo ./setup.py install`

**Comment by jhdewitt** [comment]
>One interesting thing is if i run from gui as i attempt to close the file i get some files generated each time i press the x to close
>np,urlib,sys,cv2.os,time,optparse
>They have a header with color info then a bunch of codes at

Now this one, has me stumped! More details needed.

**Comment by prahjister** [comment]
after install pyosc

prahjister@amlogic:~/sltk-master$ python slcapture.py
Traceback (most recent call last):
  File "slcapture.py", line 827, in <module>
    client_display.connect( (display_server_addr, display_server_port) )
NameError: name 'display_server_addr' is not defined

**Comment by prahjister** [comment]
What version of python should i be running slcapture.py?

**Comment by jhdewitt** [comment]
Python 2

**Comment by prahjister** [comment]
I threw in an ip address and port...(not exactly sure which one)

![image](https://user-images.githubusercontent.com/11030902/38121349-ab232174-339c-11e8-934f-6bbb62310c99.png)

**Comment by jhdewitt** [comment]
yay !!  small steps

`slcapture` continuously streams the images from `mjpg-streamer` and discards all images except for the ones "known" to have been taken just after `sldisp` reports the pattern was shown during a capture sequence

`slcapture` asks `sldisp` for pattern `X`. some time passes, and then `sldisp` has generated the pattern and VSYNC it out to display device, after which it sends back a packet to `slcapture` saying "pattern `X` is live as of time `T`". some time passes, and `slcapture` then saves the first image it gets with a timestamp **after**  time `T`.

The program naively trusts timestamps, so if `slcapture` and `sldisp` are run on two computers with system clock offsets, it will act poorly and potentially be waiting many seconds before saving an image after a pattern has been shown.

**Comment by prahjister** [comment]
Ok great that is why no captures yet. And I think beneficial to run slcapture and sldisp on the same box
